sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.0
jobs:
  include:
    - stage: lint
      script: bundle exec rubocop
    - stage: test
      script: bundle exec rspec
stages:
  - lint
  - test
  - name: deploy
    if: branch = master
deploy:
  provider: rubygems
  secure: "o1u1a8l0Nj7etylmyD4MiOlDOHUgPLYTgPMzY7Vjcxl1vRkfpLwUl7+0L0oFQWTEIT4qsfEobvw3k9zubd/atLe5QEckB5KqZVXlp57Efl6cTvkZ72gMcdLOIyydr3MzYlmP559/b7gBdEud835r1ZcqENQDQ05PgQHzp0dMwRqx8FqvpgZIk+8us9VVxW4Jtf194Y+m/85HOFd13ryZoWbi2o1eH7f+srTa8E7oUwWbR7AqBmEHpW0h3SoZvfEJdk/q/S0VtL/9DG8O/TmwGeWRBxroF/PvLVMLouERTTErSNaAYTtC5QGGO5NgXuy9Rm5HBRIjiEtDKgS+MMmerApwRqdScjNUouGvP4JCdeC/KB/PUW3Y9JA726slA3nR3YNk6+7Bn9VIQw7OgwDjCPkl3solnpAsbM5oH5M/pmiAPYY8DhceLFTU6OQJbPUMehj2Gt3v62dgiPsnHkGWcmQsglmNrHJZ/E0a9jxrClk8JMtE3rh2+cueNEoM6fyfVN4UFKG5gHOmGm3V0vsxtcdxJECmA4kvxoX8npLz5pAwcujSk1QjjCGfv8Z+NYN8ELJATBLZCbL/1leMWTiTjKNU22tNDYFoa+cnghtjOpd/blm8fAhMK6eX+uJz6pXHZZWl+zf4j+9AH6IZDwsqXARYrE1xNDdr5WnXP2MaZII="
