sudo: false
language: ruby
rvm:
  - 2.4.1
before_install: gem install bundler -v 1.16.0
jobs:
  include:
    - stage: lint
      script: bundle exec rubocop
    - stage: test
      script: bundle exec rspec
stages:
  - lint
  - test
  - name: deploy
    if: branch = master
deploy:
  provider: rubygems
  api_key: 9c4c45a515b52e5e6d0a2b13d2a35c41
