sudo: false
language: ruby
rvm:
- 2.4.1
before_install: gem install bundler -v 1.16.0
jobs:
  include:
  - stage: lint
    script: bundle exec rubocop
  - stage: test
    script: bundle exec rspec
stages:
- lint
- test
- name: deploy
  if: branch = master
deploy:
  provider: rubygems
  # secure: o1u1a8l0Nj7etylmyD4MiOlDOHUgPLYTgPMzY7Vjcxl1vRkfpLwUl7+0L0oFQWTEIT4qsfEobvw3k9zubd/atLe5QEckB5KqZVXlp57Efl6cTvkZ72gMcdLOIyydr3MzYlmP559/b7gBdEud835r1ZcqENQDQ05PgQHzp0dMwRqx8FqvpgZIk+8us9VVxW4Jtf194Y+m/85HOFd13ryZoWbi2o1eH7f+srTa8E7oUwWbR7AqBmEHpW0h3SoZvfEJdk/q/S0VtL/9DG8O/TmwGeWRBxroF/PvLVMLouERTTErSNaAYTtC5QGGO5NgXuy9Rm5HBRIjiEtDKgS+MMmerApwRqdScjNUouGvP4JCdeC/KB/PUW3Y9JA726slA3nR3YNk6+7Bn9VIQw7OgwDjCPkl3solnpAsbM5oH5M/pmiAPYY8DhceLFTU6OQJbPUMehj2Gt3v62dgiPsnHkGWcmQsglmNrHJZ/E0a9jxrClk8JMtE3rh2+cueNEoM6fyfVN4UFKG5gHOmGm3V0vsxtcdxJECmA4kvxoX8npLz5pAwcujSk1QjjCGfv8Z+NYN8ELJATBLZCbL/1leMWTiTjKNU22tNDYFoa+cnghtjOpd/blm8fAhMK6eX+uJz6pXHZZWl+zf4j+9AH6IZDwsqXARYrE1xNDdr5WnXP2MaZII=
env:
  global:
    secure: kpBsWr4dlbNKYmeAn8jah8qjmFiNh2PR0c/jPoa0ob+HTunz5+CbE2tL7xQaq4qI29cD56chuqo1m50fOnQx7isCJ2RXY/2flPXk6LgdbpJUOe5wtAtlIPsADnCjxRkiGt337Dy2UQuh2bdm3wp/lkyCmLC8HSmFQEftRwUaAKR2oUWWzOKM/iO5vdFt1f8CmI7aaQjwbxBZaDdFjEAbNa+g6+DYVQChEE9oIhiCBCi4UZ6Rc4G1+P7st9vnVzQkJMJ3pDnpVszHtAVTJI+vMTM9fwpyDUrBvo6QPU1z8z5OtWmU/q7YSzkLQOiCGuTg8Hy41PdPVJ06Eamt8//HeVp/wi3NDC/u7fS5NwnxuB2P5z5gfuPw41iqrkWR6pDtKKM6uOucVo4PAJwf67faXGuBMMkoE0yrUtHV0k8lxjgXhAPle3MpqeFkb6jwsWLvdbbmQ7LXKNNNEYtQ6OkrE3KjGL34+N2DkvvFf8ZRlyRUX/sS+OWct6oaeq83lciZLyR4UQ95BCA4p1kARn+lElEdaUHTg8PH+6A5xijFArggS1/h/tKGXsG7BO8yOhgMzYN6jU8T3dklNks+ixGQVGXxEv4LRiJoWBc0FGU40SekTrXSa1bqpXgpl67VBzdhysCjMEQ8bzI46QGV5VNy2uBqmw4883+1sRO38PNvsrA=
